# Generated by Django 6.0.5 on 2026-05-27 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=50)),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('codigo_postal_fiscal', models.CharField(max_length=10)),
                ('uso_cfdi', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_emisor', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=255)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('codigo_postal_expedicion', models.CharField(max_length=10)),
                ('certificado_csd', models.CharField(max_length=255)),
                ('clave_producto_sat', models.CharField(max_length=50)),
                ('clave_unidad_sat', models.CharField(max_length=50)),
                ('objeto_impuesto', models.CharField(max_length=100)),
                ('iva_default', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forma_pago', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tickets/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('forma_pago_detectada', models.CharField(blank=True, max_length=100, null=True)),
                ('text_length', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_api.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='images_api.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
